"""Add paid_amount and created_date to Transaction

Revision ID: 7d8a12e55b72
Revises: 4bdf27bab6fe
Create Date: 2025-08-20 16:36:36.444953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8a12e55b72'
down_revision = '4bdf27bab6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('created_date')
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
