"""tables for person , event , transaction are added

Revision ID: db57548843c0
Revises: dbcd7d751e7f
Create Date: 2025-03-23 23:31:26.380298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db57548843c0'
down_revision = 'dbcd7d751e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_name')
    )
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('person_name')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('person')
    op.drop_table('event')
    # ### end Alembic commands ###
